sudo: false
language: php

php:
    - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer install
  - mysql -e 'create database phpauth_db;'
  - mysql -u root phpauth_db < phpauth_db.sql

script:
    - phpunit

notifications:
    email: false